{{- if .Values.azure.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-azure
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  storageAccount: {{ .Values.azure.storageAccount | b64enc }}
  storageAccessKey:  {{ .Values.azure.storageAccessKey | b64enc }}
{{- end }}
